// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260817155456_NormalizeMigratedLocationIds")]
    partial class NormalizeMigratedLocationIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Domain.AccountingPeriods.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AccountingPeriods");
                });

            modelBuilder.Entity("Domain.AccountingPeriods.AccountingPeriodBalanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountingPeriodId");

                    b.ToTable("AccountingPeriodBalanceHistories");
                });

            modelBuilder.Entity("Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOpened")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinancialInstitution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OnboardedBalance")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpeningAccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Domain.Accounts.AccountBalanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PostedBalance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Date", "Sequence")
                        .IsUnique();

                    b.ToTable("AccountBalanceHistories");
                });

            modelBuilder.Entity("Domain.Accounts.PendingAccountBalanceEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingCreditAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingDebitAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId", "AccountId")
                        .IsUnique();

                    b.ToTable("PendingAccountBalanceEffects");
                });

            modelBuilder.Entity("Domain.FundGoals.FundGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumFundedBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumFundedBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegularContribution")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetEndingBalance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountingPeriodId");

                    b.HasIndex("FundId")
                        .IsUnique()
                        .HasFilter("\"AccountingPeriodId\" IS NULL");

                    b.HasIndex("FundId", "AccountingPeriodId")
                        .IsUnique();

                    b.ToTable("FundGoals");
                });

            modelBuilder.Entity("Domain.FundGoals.FundGoalTotalsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountAssigned")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountSpent")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularAmountAssigned")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "AccountingPeriodId", "Date", "Sequence")
                        .IsUnique();

                    b.ToTable("FundGoalTotalsHistories");
                });

            modelBuilder.Entity("Domain.FundGoals.PendingFundGoalTotalsEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingAmountAssigned")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingAmountSpent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingRegularAmountAssigned")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "AccountingPeriodId");

                    b.HasIndex("TransactionId", "FundId", "AccountingPeriodId")
                        .IsUnique();

                    b.ToTable("PendingFundGoalTotalsEffects");
                });

            modelBuilder.Entity("Domain.Funds.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OnboardedBalance")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpeningAccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("Domain.Funds.FundBalanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PostedBalance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "Date", "Sequence")
                        .IsUnique();

                    b.ToTable("FundBalanceHistories");
                });

            modelBuilder.Entity("Domain.Funds.PendingFundBalanceEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingCreditAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingDebitAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.HasIndex("TransactionId", "FundId")
                        .IsUnique();

                    b.ToTable("PendingFundBalanceEffects");
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Sequence")
                        .IsUnique();

                    b.ToTable("Transactions");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Users.UserAdministrationAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemActor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewRole")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousRole")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetInvitationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TargetInvitationId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserAdministrationAuditEvents");
                });

            modelBuilder.Entity("Domain.Users.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("NormalizedEmail", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("UserInvitations");
                });

            modelBuilder.Entity("Domain.Transactions.Accounts.AccountTransaction", b =>
                {
                    b.HasBaseType("Domain.Transactions.Transaction");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Transactions.Funds.FundTransaction", b =>
                {
                    b.HasBaseType("Domain.Transactions.Transaction");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.Transactions.Income.IncomeTransaction", b =>
                {
                    b.HasBaseType("Domain.Transactions.Transaction");

                    b.Property<decimal>("TrackedAmount")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Transactions.Spending.SpendingTransaction", b =>
                {
                    b.HasBaseType("Domain.Transactions.Transaction");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Domain.AccountingPeriods.AccountingPeriod", b =>
                {
                    b.OwnsMany("Domain.AccountingPeriods.ExpectedIncomeSource", "ExpectedIncomeSources", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountingPeriodId");

                            b1.ToTable("ExpectedIncomeSources", (string)null);

                            b1.WithOwner("AccountingPeriod")
                                .HasForeignKey("AccountingPeriodId");

                            b1.OwnsMany("Domain.AccountingPeriods.ExpectedIncomeDate", "ExpectedDates", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ExpectedIncomeSourceId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExpectedIncomeSourceId");

                                    b2.ToTable("ExpectedIncomeSourceDates", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExpectedIncomeSourceId");
                                });

                            b1.OwnsMany("Domain.Transactions.Income.IncomeDeduction", "IncomeDeductions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ExpectedIncomeSourceId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExpectedIncomeSourceId");

                                    b2.ToTable("ExpectedIncomeSourceIncomeDeductions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExpectedIncomeSourceId");
                                });

                            b1.OwnsMany("Domain.Transactions.Income.IncomeLine", "IncomeLines", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ExpectedIncomeSourceId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExpectedIncomeSourceId");

                                    b2.ToTable("ExpectedIncomeSourceIncomeLines", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExpectedIncomeSourceId");
                                });

                            b1.OwnsMany("Domain.AccountingPeriods.ExpectedUntrackedIncomeTransfer", "UntrackedTransfers", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ExpectedIncomeSourceId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExpectedIncomeSourceId");

                                    b2.ToTable("ExpectedIncomeSourceUntrackedTransfers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExpectedIncomeSourceId");
                                });

                            b1.Navigation("AccountingPeriod");

                            b1.Navigation("ExpectedDates");

                            b1.Navigation("IncomeDeductions");

                            b1.Navigation("IncomeLines");

                            b1.Navigation("UntrackedTransfers");
                        });

                    b.Navigation("ExpectedIncomeSources");
                });

            modelBuilder.Entity("Domain.AccountingPeriods.AccountingPeriodBalanceHistory", b =>
                {
                    b.HasOne("Domain.AccountingPeriods.AccountingPeriod", "AccountingPeriod")
                        .WithMany()
                        .HasForeignKey("AccountingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.AccountingPeriods.AccountingPeriodAccountBalanceHistory", "AccountBalances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodBalanceHistoryId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("ClosingBalance")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("OpeningBalance")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("AccountingPeriodBalanceHistoryId");

                            b1.HasIndex("AccountingPeriodId");

                            b1.ToTable("AccountingPeriodAccountBalanceHistory");

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("AccountingPeriodBalanceHistoryId");

                            b1.HasOne("Domain.AccountingPeriods.AccountingPeriod", "AccountingPeriod")
                                .WithMany()
                                .HasForeignKey("AccountingPeriodId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Account");

                            b1.Navigation("AccountingPeriod");
                        });

                    b.OwnsMany("Domain.AccountingPeriods.AccountingPeriodFundBalanceHistory", "FundBalances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodBalanceHistoryId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("ClosingBalance")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("OpeningBalance")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountingPeriodBalanceHistoryId");

                            b1.HasIndex("AccountingPeriodId");

                            b1.HasIndex("FundId");

                            b1.ToTable("AccountingPeriodFundBalanceHistory");

                            b1.WithOwner()
                                .HasForeignKey("AccountingPeriodBalanceHistoryId");

                            b1.HasOne("Domain.AccountingPeriods.AccountingPeriod", "AccountingPeriod")
                                .WithMany()
                                .HasForeignKey("AccountingPeriodId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("Domain.Funds.Fund", "Fund")
                                .WithMany()
                                .HasForeignKey("FundId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("AccountingPeriod");

                            b1.Navigation("Fund");
                        });

                    b.OwnsMany("Domain.AccountingPeriods.AccountingPeriodFundGoalTotals", "FundGoalTotals", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodBalanceHistoryId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountingPeriodId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AmountAssigned")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AmountSpent")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("RegularAmountAssigned")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountingPeriodBalanceHistoryId");

                            b1.HasIndex("AccountingPeriodId");

                            b1.HasIndex("FundId");

                            b1.ToTable("AccountingPeriodFundGoalTotals");

                            b1.WithOwner()
                                .HasForeignKey("AccountingPeriodBalanceHistoryId");

                            b1.HasOne("Domain.AccountingPeriods.AccountingPeriod", "AccountingPeriod")
                                .WithMany()
                                .HasForeignKey("AccountingPeriodId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("Domain.Funds.Fund", "Fund")
                                .WithMany()
                                .HasForeignKey("FundId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("AccountingPeriod");

                            b1.Navigation("Fund");
                        });

                    b.Navigation("AccountBalances");

                    b.Navigation("AccountingPeriod");

                    b.Navigation("FundBalances");

                    b.Navigation("FundGoalTotals");
                });

            modelBuilder.Entity("Domain.Accounts.AccountBalanceHistory", b =>
                {
                    b.HasOne("Domain.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Accounts.PendingAccountBalanceEffect", b =>
                {
                    b.HasOne("Domain.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.FundGoals.FundGoal", b =>
                {
                    b.HasOne("Domain.AccountingPeriods.AccountingPeriod", "AccountingPeriod")
                        .WithMany()
                        .HasForeignKey("AccountingPeriodId");

                    b.HasOne("Domain.Funds.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountingPeriod");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Domain.Funds.FundBalanceHistory", b =>
                {
                    b.HasOne("Domain.Funds.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Domain.Funds.PendingFundBalanceEffect", b =>
                {
                    b.HasOne("Domain.Funds.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Domain.Users.UserAdministrationAuditEvent", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Users.UserInvitation", null)
                        .WithMany()
                        .HasForeignKey("TargetInvitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Users.UserInvitation", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Transactions.Accounts.AccountTransaction", b =>
                {
                    b.OwnsMany("Domain.Transactions.Accounts.AccountTransactionDestination", "Destinations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid?>("AccountId")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreditAccountId");

                            b1.Property<Guid>("AccountTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.Property<Guid?>("LocationId")
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationId");

                            b1.Property<DateOnly?>("PostedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreditPostedDate");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("AccountTransactionId");

                            b1.HasIndex("LocationId");

                            b1.ToTable("AccountTransactionDestinations", (string)null);

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId");

                            b1.WithOwner()
                                .HasForeignKey("AccountTransactionId");

                            b1.HasOne("Domain.Locations.Location", "Location")
                                .WithMany()
                                .HasForeignKey("LocationId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("Account");

                            b1.Navigation("Location");
                        });

                    b.OwnsOne("Domain.Transactions.Accounts.AccountTransactionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("AccountTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("AccountId")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccountTransaction_DebitAccountId");

                            b1.Property<Guid?>("LocationId")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccountTransaction_SourceLocationId");

                            b1.Property<DateOnly?>("PostedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccountTransaction_DebitPostedDate");

                            b1.HasKey("AccountTransactionId");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("LocationId");

                            b1.ToTable("Transactions");

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId");

                            b1.WithOwner()
                                .HasForeignKey("AccountTransactionId");

                            b1.HasOne("Domain.Locations.Location", "Location")
                                .WithMany()
                                .HasForeignKey("LocationId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("Account");

                            b1.Navigation("Location");
                        });

                    b.Navigation("Destinations");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Transactions.Funds.FundTransaction", b =>
                {
                    b.OwnsMany("Domain.Transactions.Funds.FundTransactionDestination", "Destinations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreditFundId");

                            b1.Property<Guid>("FundTransactionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("FundId");

                            b1.HasIndex("FundTransactionId");

                            b1.ToTable("FundTransactionDestinations", (string)null);

                            b1.HasOne("Domain.Funds.Fund", "Fund")
                                .WithMany()
                                .HasForeignKey("FundId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("FundTransactionId");

                            b1.Navigation("Fund");
                        });

                    b.OwnsOne("Domain.Transactions.Funds.FundTransactionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("FundTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("TEXT")
                                .HasColumnName("FundTransaction_DebitFundId");

                            b1.HasKey("FundTransactionId");

                            b1.HasIndex("FundId");

                            b1.ToTable("Transactions");

                            b1.HasOne("Domain.Funds.Fund", "Fund")
                                .WithMany()
                                .HasForeignKey("FundId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("FundTransactionId");

                            b1.Navigation("Fund");
                        });

                    b.Navigation("Destinations");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Transactions.Income.IncomeTransaction", b =>
                {
                    b.OwnsMany("Domain.Transactions.Income.IncomeTransactionDestination", "Destinations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("IncomeTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("PostedDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("IncomeTransactionId");

                            b1.ToTable("IncomeTransactionIncomeDestinations", (string)null);

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("IncomeTransactionId");

                            b1.OwnsMany("Domain.Transactions.Income.IncomeFundAmount", "FundAssignments", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("FundId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("IncomeDestinationId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsExtraContribution")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("Id");

                                    b2.HasIndex("IncomeDestinationId");

                                    b2.ToTable("IncomeTransactionIncomeDestinationFundAssignments", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("IncomeDestinationId");
                                });

                            b1.Navigation("Account");

                            b1.Navigation("FundAssignments");
                        });

                    b.OwnsOne("Domain.Transactions.Income.IncomeTransactionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("IncomeTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("AccountId")
                                .HasColumnType("TEXT")
                                .HasColumnName("IncomeTransaction_SourceAccountId");

                            b1.Property<Guid?>("LocationId")
                                .HasColumnType("TEXT")
                                .HasColumnName("IncomeTransaction_SourceLocationId");

                            b1.Property<DateOnly?>("PostedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("IncomeTransaction_SourcePostedDate");

                            b1.HasKey("IncomeTransactionId");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("LocationId");

                            b1.ToTable("Transactions");

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId");

                            b1.WithOwner()
                                .HasForeignKey("IncomeTransactionId");

                            b1.HasOne("Domain.Locations.Location", "Location")
                                .WithMany()
                                .HasForeignKey("LocationId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.OwnsMany("Domain.Transactions.Income.IncomeDeduction", "IncomeDeductions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid?>("IncomeTransactionId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("IncomeTransactionId");

                                    b2.ToTable("IncomeTransactionIncomeDeductions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("IncomeTransactionId");
                                });

                            b1.OwnsMany("Domain.Transactions.Income.IncomeLine", "IncomeLines", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid?>("IncomeTransactionId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("IncomeTransactionId");

                                    b2.ToTable("IncomeTransactionIncomeLines", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("IncomeTransactionId");
                                });

                            b1.Navigation("Account");

                            b1.Navigation("IncomeDeductions");

                            b1.Navigation("IncomeLines");

                            b1.Navigation("Location");
                        });

                    b.Navigation("Destinations");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Transactions.Spending.SpendingTransaction", b =>
                {
                    b.OwnsMany("Domain.Transactions.Spending.SpendingTransactionDestination", "Destinations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid?>("AccountId")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreditAccountId");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.Property<Guid?>("LocationId")
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationId");

                            b1.Property<DateOnly?>("PostedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreditPostedDate");

                            b1.Property<Guid>("SpendingTransactionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("LocationId");

                            b1.HasIndex("SpendingTransactionId");

                            b1.ToTable("SpendingTransactionDestinations", (string)null);

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId");

                            b1.HasOne("Domain.Locations.Location", "Location")
                                .WithMany()
                                .HasForeignKey("LocationId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("SpendingTransactionId");

                            b1.OwnsMany("Domain.Funds.FundAmount", "FundAssignments", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("DestinationId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("FundId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DestinationId");

                                    b2.ToTable("SpendingTransactionDestinationFundAssignments", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("DestinationId");
                                });

                            b1.Navigation("Account");

                            b1.Navigation("FundAssignments");

                            b1.Navigation("Location");
                        });

                    b.OwnsOne("Domain.Transactions.Spending.SpendingTransactionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("SpendingTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("TEXT")
                                .HasColumnName("SpendingTransaction_DebitAccountId");

                            b1.Property<DateOnly?>("PostedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("SpendingTransaction_DebitPostedDate");

                            b1.HasKey("SpendingTransactionId");

                            b1.HasIndex("AccountId");

                            b1.ToTable("Transactions");

                            b1.HasOne("Domain.Accounts.Account", "Account")
                                .WithMany()
                                .HasForeignKey("AccountId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SpendingTransactionId");

                            b1.Navigation("Account");
                        });

                    b.Navigation("Destinations");

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}