"""Render a checked-in or local environment template."""

from __future__ import annotations

import secrets
import shlex
from argparse import Namespace
from pathlib import Path

from ..core.context import Context
from .common import ensure_directory
from .env_support import schema


def _configure_debug_paths(context: Context, output: Path) -> None:
    """Keep generated native-debug paths usable by every debug process."""

    values = {
        "DATABASE_PATH": str(context.paths.debug_database),
        "LOG_DIRECTORY": str(context.paths.debug_logs),
    }
    lines = output.read_text(encoding="utf-8").splitlines()
    remaining = set(values)
    configured: list[str] = []

    for line in lines:
        name = line.split("=", 1)[0].strip() if "=" in line else ""
        if name in values and not line.lstrip().startswith("#"):
            configured.append(f"{name}={shlex.quote(values[name])}")
            remaining.discard(name)
        else:
            configured.append(line)

    if remaining:
        if configured and configured[-1].strip():
            configured.append("")
        configured.extend(
            f"{name}={shlex.quote(values[name])}" for name in sorted(remaining)
        )

    output.write_text("\n".join(configured) + "\n", encoding="utf-8")
    output.chmod(0o600)


def run(context: Context, args: Namespace) -> int:
    output = (
        Path(args.output)
        if args.output
        else (
            context.paths.debug_environment
            if args.profile == "debug"
            else context.paths.production_template
        )
    )
    if output.exists() and not args.force:
        if args.profile == "debug":
            _configure_debug_paths(context, output)
        print(f"Keeping existing environment file: {output}")
        return 0
    ensure_directory(output.parent)
    loaded_schema = schema(context)
    lines = [f"# Generated by `ft env render --profile {args.profile}`.", ""]
    for variable in loaded_schema.rendered_variables(args.profile):
        value = variable.default_for(args.profile)
        if args.profile == "debug" and variable.name == "AUTH_SECRET":
            value = secrets.token_urlsafe(48)
        lines.append(f"{variable.name}={shlex.quote(value)}")
    template = "\n".join(lines) + "\n"
    output.write_text(template, encoding="utf-8")
    if args.profile == "debug":
        _configure_debug_paths(context, output)
    print(f"Environment file written: {output}")
    return 0
