/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"][];
                        "application/json": components["schemas"]["FundModel"][];
                        "text/json": components["schemas"]["FundModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "text/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "application/*+json": components["schemas"]["CreateOrUpdateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "text/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "application/*+json": components["schemas"]["CreateOrUpdateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrUpdateFundModel: {
            name: string;
            description: string;
        };
        /** @enum {unknown} */
        ErrorCode: "Generic" | "InvalidFundName";
        ErrorDetailModel: {
            errorCode: components["schemas"]["ErrorCode"];
            description: string;
        };
        ErrorModel: {
            message: string;
            details: components["schemas"]["ErrorDetailModel"][];
        };
        FundModel: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
