/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountModel"][];
                        "application/json": components["schemas"]["AccountModel"][];
                        "text/json": components["schemas"]["AccountModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountModel"];
                    "text/json": components["schemas"]["CreateAccountModel"];
                    "application/*+json": components["schemas"]["CreateAccountModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountModel"];
                        "application/json": components["schemas"]["AccountModel"];
                        "text/json": components["schemas"]["AccountModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountModel"];
                    "text/json": components["schemas"]["UpdateAccountModel"];
                    "application/*+json": components["schemas"]["UpdateAccountModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountModel"];
                        "application/json": components["schemas"]["AccountModel"];
                        "text/json": components["schemas"]["AccountModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"][];
                        "application/json": components["schemas"]["AccountingPeriodModel"][];
                        "text/json": components["schemas"]["AccountingPeriodModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountingPeriodModel"];
                    "text/json": components["schemas"]["CreateAccountingPeriodModel"];
                    "application/*+json": components["schemas"]["CreateAccountingPeriodModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"];
                        "application/json": components["schemas"]["AccountingPeriodModel"];
                        "text/json": components["schemas"]["AccountingPeriodModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"];
                        "application/json": components["schemas"]["AccountingPeriodModel"];
                        "text/json": components["schemas"]["AccountingPeriodModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"][];
                        "application/json": components["schemas"]["FundModel"][];
                        "text/json": components["schemas"]["FundModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "text/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "application/*+json": components["schemas"]["CreateOrUpdateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "text/json": components["schemas"]["CreateOrUpdateFundModel"];
                    "application/*+json": components["schemas"]["CreateOrUpdateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorModel"];
                        "application/json": components["schemas"]["ErrorModel"];
                        "text/json": components["schemas"]["ErrorModel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountingPeriodModel: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            month: number;
            isOpen: boolean;
        };
        AccountModel: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["AccountTypeModel"];
        };
        /** @enum {unknown} */
        AccountTypeModel: AccountTypeModel;
        CreateAccountingPeriodModel: {
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            month: number;
        };
        CreateAccountModel: {
            name: string;
            type: components["schemas"]["AccountTypeModel"];
            /** Format: uuid */
            accountingPeriodId: string;
            /** Format: date */
            addDate: string;
            initialFundAmounts: components["schemas"]["FundAmountModel"][];
        };
        CreateOrUpdateFundModel: {
            name: string;
            description: string;
        };
        /** @enum {unknown} */
        ErrorCode: ErrorCode;
        ErrorDetailModel: {
            errorCode: components["schemas"]["ErrorCode"];
            description: string;
        };
        ErrorModel: {
            message: string;
            details: components["schemas"]["ErrorDetailModel"][];
        };
        FundAmountModel: {
            /** Format: uuid */
            fundId: string;
            /** Format: double */
            amount: number;
        };
        FundModel: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
        };
        UpdateAccountModel: {
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum AccountTypeModel {
    Standard = "Standard",
    Debt = "Debt"
}
export enum ErrorCode {
    Generic = "Generic",
    InvalidFundName = "InvalidFundName",
    InvalidAccountingPeriodYear = "InvalidAccountingPeriodYear",
    InvalidAccountingPeriodMonth = "InvalidAccountingPeriodMonth",
    InvalidAccountName = "InvalidAccountName"
}
export type operations = Record<string, never>;
