/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accountBalance/{accountId}/ByDate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DateRangeModel"];
                    "text/json": components["schemas"]["DateRangeModel"];
                    "application/*+json": components["schemas"]["DateRangeModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountModel"][];
                        "application/json": components["schemas"]["AccountModel"][];
                        "text/json": components["schemas"]["AccountModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountModel"];
                    "text/json": components["schemas"]["CreateAccountModel"];
                    "application/*+json": components["schemas"]["CreateAccountModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accountingPeriods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"][];
                        "application/json": components["schemas"]["AccountingPeriodModel"][];
                        "text/json": components["schemas"]["AccountingPeriodModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountingPeriodModel"];
                    "text/json": components["schemas"]["CreateAccountingPeriodModel"];
                    "application/*+json": components["schemas"]["CreateAccountingPeriodModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accountingPeriods/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accountingPeriods/close/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changeInValues/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changeInValues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChangeInValueModel"];
                    "text/json": components["schemas"]["CreateChangeInValueModel"];
                    "application/*+json": components["schemas"]["CreateChangeInValueModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"][];
                        "application/json": components["schemas"]["FundModel"][];
                        "text/json": components["schemas"]["FundModel"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFundModel"];
                    "text/json": components["schemas"]["CreateFundModel"];
                    "application/*+json": components["schemas"]["CreateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fundConversions/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fundConversions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFundConversionModel"];
                    "text/json": components["schemas"]["CreateFundConversionModel"];
                    "application/*+json": components["schemas"]["CreateFundConversionModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTransactionModel"];
                    "text/json": components["schemas"]["CreateTransactionModel"];
                    "application/*+json": components["schemas"]["CreateTransactionModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostTransactionModel"];
                    "text/json": components["schemas"]["PostTransactionModel"];
                    "application/*+json": components["schemas"]["PostTransactionModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountingPeriodModel: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            month: number;
            isOpen: boolean;
        };
        AccountModel: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["AccountType"];
        };
        /** @enum {unknown} */
        AccountType: "Standard" | "Debt";
        CreateAccountingPeriodModel: {
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            month: number;
        };
        CreateAccountModel: {
            name: string;
            type: components["schemas"]["AccountType"];
            /** Format: uuid */
            accountingPeriodId: string;
            /** Format: date */
            date: string;
            startingFundBalances: components["schemas"]["CreateFundAmountModel"][];
        };
        CreateChangeInValueModel: {
            /** Format: uuid */
            accountingPeriodId: string;
            /** Format: date */
            eventDate: string;
            /** Format: uuid */
            accountId: string;
            fundAmount: components["schemas"]["CreateFundAmountModel"];
        };
        CreateFundAmountModel: {
            /** Format: uuid */
            fundId: string;
            /** Format: double */
            amount: number;
        };
        CreateFundConversionModel: {
            /** Format: uuid */
            accountingPeriodId: string;
            /** Format: date */
            eventDate: string;
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            fromFundId: string;
            /** Format: uuid */
            toFundId: string;
            /** Format: double */
            amount: number;
        };
        CreateFundModel: {
            name: string;
            description: string;
        };
        CreateTransactionModel: {
            /** Format: uuid */
            accountingPeriodId: string;
            /** Format: date */
            date: string;
            /** Format: uuid */
            debitAccountId?: string | null;
            debitFundAmounts?: components["schemas"]["CreateFundAmountModel"][] | null;
            /** Format: uuid */
            creditAccountId?: string | null;
            creditFundAmounts?: unknown[] | null;
        };
        DateRangeModel: {
            /** Format: date */
            startDate: string;
            startDateType: components["schemas"]["EndpointType"];
            /** Format: date */
            endDate: string;
            endDateType: components["schemas"]["EndpointType"];
        };
        /** @enum {unknown} */
        EndpointType: "Inclusive" | "Exclusive";
        FundModel: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
        };
        PostTransactionModel: {
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            postedStatementDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
