/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the Accounts that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Search to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["AccountSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfAccountModel"];
                        "application/json": components["schemas"]["CollectionModelOfAccountModel"];
                        "text/json": components["schemas"]["CollectionModelOfAccountModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a new Account with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountModel"];
                    "text/json": components["schemas"]["CreateAccountModel"];
                    "application/*+json": components["schemas"]["CreateAccountModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountModel"];
                        "application/json": components["schemas"]["AccountModel"];
                        "text/json": components["schemas"]["AccountModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Transactions for the Account that matches the provided ID */
        get: {
            parameters: {
                query?: {
                    /** @description Search to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["AccountTransactionSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfTransactionModel"];
                        "application/json": components["schemas"]["CollectionModelOfTransactionModel"];
                        "text/json": components["schemas"]["CollectionModelOfTransactionModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Updates the provided Account with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountModel"];
                    "text/json": components["schemas"]["UpdateAccountModel"];
                    "application/*+json": components["schemas"]["UpdateAccountModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountModel"];
                        "application/json": components["schemas"]["AccountModel"];
                        "text/json": components["schemas"]["AccountModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /** Deletes the Account with the provided ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Accounting Period that matches the provided ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"];
                        "application/json": components["schemas"]["AccountingPeriodModel"];
                        "text/json": components["schemas"]["AccountingPeriodModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Deletes the Accounting Period with the provided ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the Accounting Period to delete */
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Accounting Periods that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Search string to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["AccountingPeriodSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfAccountingPeriodModel"];
                        "application/json": components["schemas"]["CollectionModelOfAccountingPeriodModel"];
                        "text/json": components["schemas"]["CollectionModelOfAccountingPeriodModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a new Accounting Period with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request to create an Accounting Period */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountingPeriodModel"];
                    "text/json": components["schemas"]["CreateAccountingPeriodModel"];
                    "application/*+json": components["schemas"]["CreateAccountingPeriodModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"];
                        "application/json": components["schemas"]["AccountingPeriodModel"];
                        "text/json": components["schemas"]["AccountingPeriodModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves all the open Accounting Periods from the database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"][];
                        "application/json": components["schemas"]["AccountingPeriodModel"][];
                        "text/json": components["schemas"]["AccountingPeriodModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Funds for the Accounting Period that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Search string to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["AccountingPeriodFundSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfAccountingPeriodFundModel"];
                        "application/json": components["schemas"]["CollectionModelOfAccountingPeriodFundModel"];
                        "text/json": components["schemas"]["CollectionModelOfAccountingPeriodFundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Accounts for the Accounting Period that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Search string to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["AccountingPeriodAccountSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfAccountingPeriodAccountModel"];
                        "application/json": components["schemas"]["CollectionModelOfAccountingPeriodAccountModel"];
                        "text/json": components["schemas"]["CollectionModelOfAccountingPeriodAccountModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Transactions for the Accounting Period that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Search string to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["AccountingPeriodTransactionSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path: {
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfTransactionModel"];
                        "application/json": components["schemas"]["CollectionModelOfTransactionModel"];
                        "text/json": components["schemas"]["CollectionModelOfTransactionModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting-periods/{accountingPeriodId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Closes the Accounting Period with the provided ID */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the Accounting Period to close */
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodModel"];
                        "application/json": components["schemas"]["AccountingPeriodModel"];
                        "text/json": components["schemas"]["AccountingPeriodModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Funds that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Search to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["FundSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfFundModel"];
                        "application/json": components["schemas"]["CollectionModelOfFundModel"];
                        "text/json": components["schemas"]["CollectionModelOfFundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a new Fund with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFundModel"];
                    "text/json": components["schemas"]["CreateFundModel"];
                    "application/*+json": components["schemas"]["CreateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fundId}/{accountingPeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Fund as it appeared in the provided Accounting Period */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                    accountingPeriodId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountingPeriodFundModel"];
                        "application/json": components["schemas"]["AccountingPeriodFundModel"];
                        "text/json": components["schemas"]["AccountingPeriodFundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fundId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Transactions for the Fund that match the specified criteria */
        get: {
            parameters: {
                query?: {
                    /** @description Accounting Period ID to filter the Transactions by */
                    AccountingPeriodId?: string;
                    /** @description Search to apply to the results */
                    Search?: string;
                    /** @description Sort to apply to the results */
                    Sort?: components["schemas"]["FundTransactionSortOrderModel"];
                    /** @description Maximum number of results to return */
                    Limit?: number;
                    /** @description Number of results to skip */
                    Offset?: number;
                };
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CollectionModelOfTransactionModel"];
                        "application/json": components["schemas"]["CollectionModelOfTransactionModel"];
                        "text/json": components["schemas"]["CollectionModelOfTransactionModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Updates the provided Fund with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateFundModel"];
                    "text/json": components["schemas"]["UpdateFundModel"];
                    "application/*+json": components["schemas"]["UpdateFundModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FundModel"];
                        "application/json": components["schemas"]["FundModel"];
                        "text/json": components["schemas"]["FundModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        /** Deletes the Fund with the provided ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new Transaction with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTransactionModel"];
                    "text/json": components["schemas"]["CreateTransactionModel"];
                    "application/*+json": components["schemas"]["CreateTransactionModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionModel"];
                        "application/json": components["schemas"]["TransactionModel"];
                        "text/json": components["schemas"]["TransactionModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Updates the provided Transaction with the provided properties */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTransactionModel"];
                    "text/json": components["schemas"]["UpdateTransactionModel"];
                    "application/*+json": components["schemas"]["UpdateTransactionModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionModel"];
                        "application/json": components["schemas"]["TransactionModel"];
                        "text/json": components["schemas"]["TransactionModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        /** Deletes the Transaction with the provided ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transactionId}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Posts the provided Transaction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostTransactionModel"];
                    "text/json": components["schemas"]["PostTransactionModel"];
                    "application/*+json": components["schemas"]["PostTransactionModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionModel"];
                        "application/json": components["schemas"]["TransactionModel"];
                        "text/json": components["schemas"]["TransactionModel"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Model representing an amount associated with a particular Account */
        AccountAmountModel: {
            /**
             * Format: uuid
             * @description Account for this Account Amount
             */
            accountId: string;
            /** @description Name of the Account for this Account Amount */
            accountName: string;
            /**
             * Format: double
             * @description Amount for this Account Amount
             */
            amount: number;
        };
        /** @description Model representing an Account Balance */
        AccountBalanceModel: {
            /**
             * Format: uuid
             * @description Account ID for the Account Balance
             */
            accountId: string;
            /**
             * Format: double
             * @description Posted Balance for the Account Balance
             */
            postedBalance: number;
            /**
             * Format: double
             * @description Available to Spend Balance for the Account Balance
             */
            availableToSpend: null | number;
            /** @description Fund Balances for the Account Balance */
            fundBalances: components["schemas"]["FundAmountModel"][];
            /**
             * Format: double
             * @description Pending Debit Amount for the Account Balance
             */
            pendingDebitAmount: number;
            /** @description Pending Debits for the Account Balance */
            pendingDebits: components["schemas"]["FundAmountModel"][];
            /**
             * Format: double
             * @description Pending Credit Amount for the Account Balance
             */
            pendingCreditAmount: number;
            /** @description Pending Credits for the Account Balance */
            pendingCredits: components["schemas"]["FundAmountModel"][];
        };
        /** @description Model representing an Account in the context of a specific Accounting Period */
        AccountingPeriodAccountModel: {
            /**
             * Format: uuid
             * @description ID for the Account
             */
            id: string;
            /** @description Name for the Account */
            name: string;
            /** @description Type for the Account */
            type: components["schemas"]["AccountTypeModel"];
            /** @description Opening balance for the Account */
            openingBalance: components["schemas"]["AccountBalanceModel"];
            /** @description Closing balance for the Account */
            closingBalance: components["schemas"]["AccountBalanceModel"];
        };
        /** @enum {unknown} */
        AccountingPeriodAccountSortOrderModel: AccountingPeriodAccountSortOrderModel | null;
        /** @description Model representing a Fund in the context of a specific Accounting Period */
        AccountingPeriodFundModel: {
            /**
             * Format: uuid
             * @description ID for the Fund
             */
            id: string;
            /** @description Name for the Fund */
            name: string;
            /** @description Description for the Fund */
            description: string;
            /** @description Opening balance for the Fund */
            openingBalance: components["schemas"]["FundBalanceModel"];
            /** @description Closing balance for the Fund */
            closingBalance: components["schemas"]["FundBalanceModel"];
        };
        /** @enum {unknown} */
        AccountingPeriodFundSortOrderModel: AccountingPeriodFundSortOrderModel | null;
        /** @description Model representing an Accounting Period */
        AccountingPeriodModel: {
            /**
             * Format: uuid
             * @description ID for the Accounting Period
             */
            id: string;
            /** @description Name of the Accounting Period */
            name: string;
            /**
             * Format: int32
             * @description Year for the Accounting Period
             */
            year: number;
            /**
             * Format: int32
             * @description Month for the Accounting Period
             */
            month: number;
            /** @description True if the Accounting Period is open, false otherwise */
            isOpen: boolean;
            /**
             * Format: double
             * @description Opening balance for the Accounting Period
             */
            openingBalance: number;
            /**
             * Format: double
             * @description Closing balance for the Accounting Period
             */
            closingBalance: number;
        };
        /** @enum {unknown} */
        AccountingPeriodSortOrderModel: AccountingPeriodSortOrderModel | null;
        /** @enum {unknown} */
        AccountingPeriodTransactionSortOrderModel: AccountingPeriodTransactionSortOrderModel | null;
        /** @description Model representing an Account */
        AccountModel: {
            /**
             * Format: uuid
             * @description ID for the Account
             */
            id: string;
            /** @description Name for the Account */
            name: string;
            /** @description Type for the Account */
            type: components["schemas"]["AccountTypeModel"];
            /** @description Current Balance for the Account */
            currentBalance: components["schemas"]["AccountBalanceModel"];
        };
        /** @enum {unknown} */
        AccountSortOrderModel: AccountSortOrderModel | null;
        /** @enum {unknown} */
        AccountTransactionSortOrderModel: AccountTransactionSortOrderModel | null;
        /**
         * @description Enum representing the different Account types
         * @enum {unknown}
         */
        AccountTypeModel: AccountTypeModel;
        /** @description Model used to represent a collection of items, along with the total count of items in the collection. */
        CollectionModelOfAccountingPeriodAccountModel: {
            /** @description The collection of items. */
            items: components["schemas"]["AccountingPeriodAccountModel"][];
            /**
             * Format: int32
             * @description The total count of items in the collection, which may be greater than the number of items in the Items property if pagination is being used.
             */
            totalCount: number;
        };
        /** @description Model used to represent a collection of items, along with the total count of items in the collection. */
        CollectionModelOfAccountingPeriodFundModel: {
            /** @description The collection of items. */
            items: components["schemas"]["AccountingPeriodFundModel"][];
            /**
             * Format: int32
             * @description The total count of items in the collection, which may be greater than the number of items in the Items property if pagination is being used.
             */
            totalCount: number;
        };
        /** @description Model used to represent a collection of items, along with the total count of items in the collection. */
        CollectionModelOfAccountingPeriodModel: {
            /** @description The collection of items. */
            items: components["schemas"]["AccountingPeriodModel"][];
            /**
             * Format: int32
             * @description The total count of items in the collection, which may be greater than the number of items in the Items property if pagination is being used.
             */
            totalCount: number;
        };
        /** @description Model used to represent a collection of items, along with the total count of items in the collection. */
        CollectionModelOfAccountModel: {
            /** @description The collection of items. */
            items: components["schemas"]["AccountModel"][];
            /**
             * Format: int32
             * @description The total count of items in the collection, which may be greater than the number of items in the Items property if pagination is being used.
             */
            totalCount: number;
        };
        /** @description Model used to represent a collection of items, along with the total count of items in the collection. */
        CollectionModelOfFundModel: {
            /** @description The collection of items. */
            items: components["schemas"]["FundModel"][];
            /**
             * Format: int32
             * @description The total count of items in the collection, which may be greater than the number of items in the Items property if pagination is being used.
             */
            totalCount: number;
        };
        /** @description Model used to represent a collection of items, along with the total count of items in the collection. */
        CollectionModelOfTransactionModel: {
            /** @description The collection of items. */
            items: components["schemas"]["TransactionModel"][];
            /**
             * Format: int32
             * @description The total count of items in the collection, which may be greater than the number of items in the Items property if pagination is being used.
             */
            totalCount: number;
        };
        /** @description Model representing a request to create an Accounting Period */
        CreateAccountingPeriodModel: {
            /**
             * Format: int32
             * @description Year for the Accounting Period
             */
            year: number;
            /**
             * Format: int32
             * @description Month for the Accounting Period
             */
            month: number;
        };
        /** @description Model representing a request to create an Account. */
        CreateAccountModel: {
            /** @description Name for the Account */
            name: string;
            /** @description Description for the Account */
            type: components["schemas"]["AccountTypeModel"];
            /**
             * Format: uuid
             * @description Accounting Period that the Account is being added to
             */
            accountingPeriodId: string;
            /**
             * Format: date
             * @description Date the Account is being added
             */
            addDate: string;
            /** @description Initial amounts for each Fund associated with the Account */
            initialFundAmounts: components["schemas"]["CreateFundAmountModel"][];
        };
        /** @description Model representing a request to create a Fund Amount */
        CreateFundAmountModel: {
            /**
             * Format: uuid
             * @description Fund for this Fund Amount
             */
            fundId: string;
            /**
             * Format: double
             * @description Amount for this Fund Amount
             */
            amount: number;
        };
        /** @description Model representing a request to create a Fund */
        CreateFundModel: {
            /** @description Name for the Fund */
            name: string;
            /** @description Description for the Fund */
            description: string;
            /**
             * Format: uuid
             * @description Accounting Period that the Fund is being added to
             */
            accountingPeriodId: string;
            /**
             * Format: date
             * @description Date the Fund is being added
             */
            addDate: string;
        };
        /** @description Model representing a request to create a Transaction Account. */
        CreateTransactionAccountModel: {
            /**
             * Format: uuid
             * @description Account for the Transaction Account
             */
            accountId: string;
            /** @description Fund Amounts for the Transaction Account */
            fundAmounts: components["schemas"]["CreateFundAmountModel"][];
        };
        /** @description Model representing a request to create a Transaction. */
        CreateTransactionModel: {
            /**
             * Format: uuid
             * @description Accounting Period for the Transaction
             */
            accountingPeriodId: string;
            /**
             * Format: date
             * @description Date for the Transaction
             */
            date: string;
            /** @description Location for the Transaction */
            location: string;
            /** @description Description for the Transaction */
            description: string;
            debitAccount: null | components["schemas"]["CreateTransactionAccountModel"];
            creditAccount: null | components["schemas"]["CreateTransactionAccountModel"];
        };
        /** @description Model representing an amount associated with a particular Fund */
        FundAmountModel: {
            /**
             * Format: uuid
             * @description Fund for this Fund Amount
             */
            fundId: string;
            /** @description Name of the Fund for this Fund Amount */
            fundName: string;
            /**
             * Format: double
             * @description Amount for this Fund Amount
             */
            amount: number;
        };
        /** @description Model representing an Fund Balance */
        FundBalanceModel: {
            /**
             * Format: uuid
             * @description Fund ID for the Fund Balance
             */
            fundId: string;
            /**
             * Format: double
             * @description Posted Balance for the Fund Balance
             */
            postedBalance: number;
            /** @description Account Balances for the Fund Balance */
            accountBalances: components["schemas"]["AccountAmountModel"][];
            /**
             * Format: double
             * @description Pending Debit Amount for the Fund Balance
             */
            pendingDebitAmount: number;
            /** @description Pending Debits for the Fund Balance */
            pendingDebits: components["schemas"]["AccountAmountModel"][];
            /**
             * Format: double
             * @description Pending Credit Amount for the Fund Balance
             */
            pendingCreditAmount: number;
            /** @description Pending Credits for the Fund Balance */
            pendingCredits: components["schemas"]["AccountAmountModel"][];
        };
        /** @description Model representing a Fund */
        FundModel: {
            /**
             * Format: uuid
             * @description ID for the Fund
             */
            id: string;
            /** @description Name for the Fund */
            name: string;
            /** @description Description for the Fund */
            description: string;
            /** @description Current Balance for the Fund */
            currentBalance: components["schemas"]["FundBalanceModel"];
        };
        /** @enum {unknown} */
        FundSortOrderModel: FundSortOrderModel | null;
        /** @enum {unknown} */
        FundTransactionSortOrderModel: FundTransactionSortOrderModel | null;
        /** @description Model representing a request to post a Transaction */
        PostTransactionModel: {
            /**
             * Format: uuid
             * @description Account to post the Transaction to
             */
            accountId: string;
            /**
             * Format: date
             * @description Date for the Transaction
             */
            date: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @description Model representing a Transaction Account */
        TransactionAccountModel: {
            /**
             * Format: uuid
             * @description Account ID for the Transaction Account
             */
            accountId: string;
            /** @description Account Name for the Transaction Account */
            accountName: string;
            /**
             * Format: date
             * @description Posted Date for the Transaction Account
             */
            postedDate: null | string;
            /** @description Fund Amounts for the Transaction Account */
            fundAmounts: components["schemas"]["FundAmountModel"][];
            /** @description Previous Account Balance for the Transaction Account */
            previousAccountBalance: components["schemas"]["AccountBalanceModel"];
            /** @description New Account Balance for the Transaction Account */
            newAccountBalance: components["schemas"]["AccountBalanceModel"];
        };
        /** @description Model representing a Transaction */
        TransactionModel: {
            /**
             * Format: uuid
             * @description ID for the Transaction
             */
            id: string;
            /**
             * Format: uuid
             * @description Accounting Period ID for the Transaction
             */
            accountingPeriodId: string;
            /** @description Name of the Accounting Period for the Transaction */
            accountingPeriodName: string;
            /**
             * Format: date
             * @description Date for the Transaction
             */
            date: string;
            /** @description Location for the Transaction */
            location: string;
            /** @description Description for the Transaction */
            description: string;
            /**
             * Format: double
             * @description Amount for the Transaction
             */
            amount: number;
            debitAccount?: null | components["schemas"]["TransactionAccountModel"];
            creditAccount?: null | components["schemas"]["TransactionAccountModel"];
            /** @description Previous Fund Balances for the Transaction */
            previousFundBalances: components["schemas"]["FundBalanceModel"][];
            /** @description New Fund Balances for the Transaction */
            newFundBalances: components["schemas"]["FundBalanceModel"][];
        };
        /** @description Model representing a request to update an Account */
        UpdateAccountModel: {
            /** @description Name for the Account */
            name: string;
        };
        /** @description Model representing a request to update a Fund */
        UpdateFundModel: {
            /** @description Name for the Fund */
            name: string;
            /** @description Description for the Fund */
            description: string;
        };
        /** @description Model representing a request to update a Transaction Account. */
        UpdateTransactionAccountModel: {
            /** @description Fund Amounts for the Transaction Account */
            fundAmounts: components["schemas"]["CreateFundAmountModel"][];
        };
        /** @description Model representing a request to update a Transaction. */
        UpdateTransactionModel: {
            /**
             * Format: date
             * @description Date for the Transaction
             */
            date: string;
            /** @description Location for the Transaction */
            location: string;
            /** @description Description for the Transaction */
            description: string;
            debitAccount: null | components["schemas"]["UpdateTransactionAccountModel"];
            creditAccount: null | components["schemas"]["UpdateTransactionAccountModel"];
        };
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum AccountingPeriodAccountSortOrderModel {
    Name = "Name",
    NameDescending = "NameDescending",
    Type = "Type",
    TypeDescending = "TypeDescending",
    OpeningBalance = "OpeningBalance",
    OpeningBalanceDescending = "OpeningBalanceDescending",
    ClosingBalance = "ClosingBalance",
    ClosingBalanceDescending = "ClosingBalanceDescending"
}
export enum AccountingPeriodFundSortOrderModel {
    Name = "Name",
    NameDescending = "NameDescending",
    OpeningBalance = "OpeningBalance",
    OpeningBalanceDescending = "OpeningBalanceDescending",
    ClosingBalance = "ClosingBalance",
    ClosingBalanceDescending = "ClosingBalanceDescending"
}
export enum AccountingPeriodSortOrderModel {
    Date = "Date",
    DateDescending = "DateDescending",
    IsOpen = "IsOpen",
    IsOpenDescending = "IsOpenDescending",
    OpeningBalance = "OpeningBalance",
    OpeningBalanceDescending = "OpeningBalanceDescending",
    ClosingBalance = "ClosingBalance",
    ClosingBalanceDescending = "ClosingBalanceDescending"
}
export enum AccountingPeriodTransactionSortOrderModel {
    Date = "Date",
    DateDescending = "DateDescending",
    Location = "Location",
    LocationDescending = "LocationDescending",
    DebitAccount = "DebitAccount",
    DebitAccountDescending = "DebitAccountDescending",
    CreditAccount = "CreditAccount",
    CreditAccountDescending = "CreditAccountDescending",
    Amount = "Amount",
    AmountDescending = "AmountDescending"
}
export enum AccountSortOrderModel {
    Name = "Name",
    NameDescending = "NameDescending",
    Type = "Type",
    TypeDescending = "TypeDescending",
    PostedBalance = "PostedBalance",
    PostedBalanceDescending = "PostedBalanceDescending",
    AvailableToSpend = "AvailableToSpend",
    AvailableToSpendDescending = "AvailableToSpendDescending"
}
export enum AccountTransactionSortOrderModel {
    Date = "Date",
    DateDescending = "DateDescending",
    Location = "Location",
    LocationDescending = "LocationDescending",
    ChangeInBalance = "ChangeInBalance",
    ChangeInBalanceDescending = "ChangeInBalanceDescending"
}
export enum AccountTypeModel {
    Standard = "Standard",
    Debt = "Debt"
}
export enum FundSortOrderModel {
    Name = "Name",
    NameDescending = "NameDescending",
    Description = "Description",
    DescriptionDescending = "DescriptionDescending",
    Balance = "Balance",
    BalanceDescending = "BalanceDescending"
}
export enum FundTransactionSortOrderModel {
    Date = "Date",
    DateDescending = "DateDescending",
    Location = "Location",
    LocationDescending = "LocationDescending",
    ChangeInBalance = "ChangeInBalance",
    ChangeInBalanceDescending = "ChangeInBalanceDescending"
}
export type operations = Record<string, never>;
