<Project Sdk="Microsoft.NET.Sdk">
  <!-- Allow the Data project to access the internals of this project -->
  <ItemGroup>
    <InternalsVisibleTo Include="Data" />
    <InternalsVisibleTo Include="Tests" />
  </ItemGroup>

    <!-- Nuget Package References -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
