using System.Diagnostics.CodeAnalysis;
using Domain.AccountingPeriods;
using Domain.Accounts;
using Domain.Exceptions;
using Domain.Funds;
using Domain.Transactions.CreateRequests;
using Domain.Transactions.UpdateRequests;

namespace Domain.Transactions;

/// <summary>
/// Service for managing Transactions
/// </summary>
public class TransactionService(
    AccountBalanceService accountBalanceService,
    AccountingPeriodBalanceService accountingPeriodBalanceService,
    FundBalanceService fundBalanceService,
    IAccountingPeriodRepository accountingPeriodRepository,
    IAccountRepository accountRepository,
    ITransactionRepository transactionRepository)
{
    /// <summary>
    /// Attempts to create a new Transaction
    /// </summary>
    public bool TryCreate(CreateTransactionRequest request, [NotNullWhen(true)] out Transaction? transaction, out IEnumerable<Exception> exceptions)
    {
        transaction = null;
        exceptions = [];

        AccountingPeriod accountingPeriod = accountingPeriodRepository.GetById(request.AccountingPeriodId);
        if (!ValidateAccountingPeriod(request, accountingPeriod, out IEnumerable<Exception> accountingPeriodExceptions))
        {
            exceptions = exceptions.Concat(accountingPeriodExceptions);
        }
        if (!ValidateDate(accountingPeriod, GetRequestAccounts(request), request.TransactionDate, out IEnumerable<Exception> dateExceptions))
        {
            exceptions = exceptions.Concat(dateExceptions);
        }
        if (!ValidateFundAmounts(request, out IEnumerable<Exception> fundAmountExceptions))
        {
            exceptions = exceptions.Concat(fundAmountExceptions);
        }
        if (exceptions.Any())
        {
            return false;
        }
        int sequence = transactionRepository.GetNextSequenceForDate(request.TransactionDate);
        transaction = request switch
        {
            CreateSpendingTransferTransactionRequest r => new SpendingTransferTransaction(r, sequence),
            CreateSpendingTransactionRequest r => new SpendingTransaction(r, sequence),
            CreateIncomeTransferTransactionRequest r => new IncomeTransferTransaction(r, sequence),
            CreateIncomeTransactionRequest r => new IncomeTransaction(r, sequence),
            CreateTransferTransactionRequest r => new TransferTransaction(r, sequence),
            // CreateRefundTransactionRequest r => new RefundTransaction(r, sequence),
            _ => throw new InvalidOperationException("Unknown transaction request type")
        };
        accountBalanceService.AddTransaction(transaction);
        fundBalanceService.AddTransaction(transaction);
        transactionRepository.Add(transaction);
        foreach ((AccountId accountId, DateOnly postedDate) in GetInitialPostings(request))
        {
            if (!TryPost(transaction, accountId, postedDate, out IEnumerable<Exception> postingExceptions))
            {
                exceptions = exceptions.Concat(postingExceptions);
            }
        }
        if (exceptions.Any())
        {
            return false;
        }
        return true;
    }

    /// <summary>
    /// Attempts to update an existing Transaction
    /// </summary>
    public bool TryUpdate(Transaction transaction, UpdateTransactionRequest request, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (GetGeneratedByAccountId(transaction) != null)
        {
            exceptions = exceptions.Append(new UnableToUpdateException("The provided transaction was auto-generated by an account and cannot be updated."));
        }
        if (!ValidateNotPosted(transaction, null))
        {
            exceptions = exceptions.Append(new UnableToUpdateException("The provided transaction has already been posted to an account."));
        }
        IEnumerable<Account> accounts = transaction.GetAllAffectedAccountIds().Select(accountRepository.GetById);
        if (!ValidateDate(accountingPeriodRepository.GetById(transaction.AccountingPeriodId), accounts, request.TransactionDate, out IEnumerable<Exception> dateExceptions))
        {
            exceptions = exceptions.Concat(dateExceptions);
        }
        if (!ValidateFundAmountsForUpdate(request, out IEnumerable<Exception> fundAmountExceptions))
        {
            exceptions = exceptions.Concat(fundAmountExceptions);
        }
        if (exceptions.Any())
        {
            return false;
        }
        transaction.Date = request.TransactionDate;
        transaction.Location = request.Location;
        transaction.Description = request.Description;
        if (transaction is SpendingTransaction spendingTransaction && request is UpdateSpendingTransactionRequest spendingRequest)
        {
            spendingTransaction.UpdateFundAmounts(spendingRequest.FundAssignments);
        }
        else if (transaction is IncomeTransaction incomeTransaction && request is UpdateIncomeTransactionRequest incomeRequest)
        {
            incomeTransaction.UpdateFundAmounts(incomeRequest.FundAssignments);
        }
        accountBalanceService.UpdateTransaction(transaction);
        fundBalanceService.UpdateTransaction(transaction);
        foreach ((AccountId accountId, DateOnly postedDate) in GetUpdatePostings(transaction, request))
        {
            if (!TryPost(transaction, accountId, postedDate, out IEnumerable<Exception> postingExceptions))
            {
                exceptions = exceptions.Concat(postingExceptions);
            }
        }
        if (exceptions.Any())
        {
            return false;
        }
        return true;
    }

    /// <summary>
    /// Attempts to post an existing Transaction within an Account
    /// </summary>
    public bool TryPost(Transaction transaction, AccountId account, DateOnly postedDate, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!ValidatePosting(transaction, account, postedDate, out IEnumerable<Exception> postingExceptions))
        {
            exceptions = exceptions.Concat(postingExceptions);
            return false;
        }
        SetPostedDate(transaction, account, postedDate);
        accountingPeriodBalanceService.PostTransaction(transaction, account);
        accountBalanceService.PostTransaction(transaction, account);
        fundBalanceService.PostTransaction(transaction, account);
        return true;
    }

    /// <summary>
    /// Attempts to unpost an existing Transaction within an Account
    /// </summary>
    public bool TryUnpost(Transaction transaction, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!ValidateUnposting(transaction, out IEnumerable<Exception> unpostingExceptions))
        {
            exceptions = exceptions.Concat(unpostingExceptions);
            return false;
        }
        accountingPeriodBalanceService.UnpostTransaction(transaction);
        accountBalanceService.UnpostTransaction(transaction);
        fundBalanceService.UnpostTransaction(transaction);
        foreach (AccountId accountId in transaction.GetAllAffectedAccountIds())
        {
            ClearPostedDate(transaction, accountId);
        }
        return true;
    }

    /// <summary>
    /// Attempts to delete an existing Transaction
    /// </summary>
    public bool TryDelete(Transaction transaction, AccountId? accountBeingDeleted, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        AccountId? generatedByAccountId = GetGeneratedByAccountId(transaction);
        if (accountBeingDeleted != generatedByAccountId && generatedByAccountId != null)
        {
            exceptions = exceptions.Append(new UnableToDeleteException("The provided transaction was auto-generated by an account."));
        }
        if (!accountingPeriodRepository.GetById(transaction.AccountingPeriodId).IsOpen)
        {
            exceptions = exceptions.Append(new UnableToDeleteException("The provided transaction is within a closed accounting period."));
        }
        if (!ValidateNotPosted(transaction, accountBeingDeleted))
        {
            exceptions = exceptions.Append(new UnableToDeleteException("The provided transaction has already been posted to an account."));
        }
        if (exceptions.Any())
        {
            return false;
        }
        accountBalanceService.DeleteTransaction(transaction);
        fundBalanceService.DeleteTransaction(transaction);
        transactionRepository.Delete(transaction);
        return true;
    }

    /// <summary>
    /// Gets the AccountId that generated this transaction, or null if not auto-generated
    /// </summary>
    private static AccountId? GetGeneratedByAccountId(Transaction transaction) =>
        transaction is IncomeTransaction income ? income.GeneratedByAccountId : null;

    /// <summary>
    /// Gets all accounts referenced in a CreateTransactionRequest
    /// </summary>
    private static Account[] GetRequestAccounts(CreateTransactionRequest request) =>
        request switch
        {
            CreateSpendingTransferTransactionRequest r => new Account[] { r.Account, r.CreditAccount },
            CreateSpendingTransactionRequest r => new Account[] { r.Account },
            CreateIncomeTransferTransactionRequest r => new Account[] { r.Account, r.DebitAccount },
            CreateIncomeTransactionRequest r => new Account[] { r.Account },
            CreateTransferTransactionRequest r => new Account[] { r.DebitAccount, r.CreditAccount },
            _ => []
        };

    /// <summary>
    /// Gets the initial postings to apply after creating a transaction
    /// </summary>
    private static List<(AccountId AccountId, DateOnly PostedDate)> GetInitialPostings(CreateTransactionRequest request)
    {
        List<(AccountId, DateOnly)> postings = [];
        switch (request)
        {
            case CreateSpendingTransferTransactionRequest r:
                if (r.PostedDate != null)
                {
                    postings.Add((r.Account.Id, r.PostedDate.Value));
                }
                if (r.CreditPostedDate != null)
                {
                    postings.Add((r.CreditAccount.Id, r.CreditPostedDate.Value));
                }
                break;
            case CreateSpendingTransactionRequest r:
                if (r.PostedDate != null)
                {
                    postings.Add((r.Account.Id, r.PostedDate.Value));
                }
                break;
            case CreateIncomeTransferTransactionRequest r:
                if (r.PostedDate != null)
                {
                    postings.Add((r.Account.Id, r.PostedDate.Value));
                }
                if (r.DebitPostedDate != null)
                {
                    postings.Add((r.DebitAccount.Id, r.DebitPostedDate.Value));
                }
                break;
            case CreateIncomeTransactionRequest r:
                if (r.PostedDate != null)
                {
                    postings.Add((r.Account.Id, r.PostedDate.Value));
                }
                break;
            case CreateTransferTransactionRequest r:
                if (r.DebitPostedDate != null)
                {
                    postings.Add((r.DebitAccount.Id, r.DebitPostedDate.Value));
                }
                if (r.CreditPostedDate != null)
                {
                    postings.Add((r.CreditAccount.Id, r.CreditPostedDate.Value));
                }
                break;
            default:
                break;
        }
        return postings;
    }

    /// <summary>
    /// Gets the postings to apply during a transaction update
    /// </summary>
    private static List<(AccountId AccountId, DateOnly PostedDate)> GetUpdatePostings(Transaction transaction, UpdateTransactionRequest request)
    {
        List<(AccountId, DateOnly)> postings = [];
        switch (request)
        {
            case UpdateSpendingTransferTransactionRequest r when transaction is SpendingTransferTransaction spendingTransfer:
                if (r.PostedDate != null)
                {
                    postings.Add((spendingTransfer.AccountId, r.PostedDate.Value));
                }
                if (r.CreditPostedDate != null)
                {
                    postings.Add((spendingTransfer.CreditAccountId, r.CreditPostedDate.Value));
                }
                break;
            case UpdateSpendingTransactionRequest r when transaction is SpendingTransaction spending:
                if (r.PostedDate != null)
                {
                    postings.Add((spending.AccountId, r.PostedDate.Value));
                }
                break;
            case UpdateIncomeTransferTransactionRequest r when transaction is IncomeTransferTransaction incomeTransfer:
                if (r.PostedDate != null)
                {
                    postings.Add((incomeTransfer.AccountId, r.PostedDate.Value));
                }
                if (r.DebitPostedDate != null)
                {
                    postings.Add((incomeTransfer.DebitAccountId, r.DebitPostedDate.Value));
                }
                break;
            case UpdateIncomeTransactionRequest r when transaction is IncomeTransaction income:
                if (r.PostedDate != null)
                {
                    postings.Add((income.AccountId, r.PostedDate.Value));
                }
                break;
            case UpdateTransferTransactionRequest r when transaction is TransferTransaction transfer:
                if (r.DebitPostedDate != null)
                {
                    postings.Add((transfer.DebitAccountId, r.DebitPostedDate.Value));
                }
                if (r.CreditPostedDate != null)
                {
                    postings.Add((transfer.CreditAccountId, r.CreditPostedDate.Value));
                }
                break;
            // case UpdateRefundTransactionRequest r when transaction is RefundTransaction refund:
            //     AccountId? debitAccountId = refund.GetAllAffectedAccountIds().FirstOrDefault();
            //     AccountId? creditAccountId = refund.GetAllAffectedAccountIds().Skip(1).FirstOrDefault();
            //     if (r.DebitPostedDate != null && debitAccountId != null)
            //     {
            //         postings.Add((debitAccountId, r.DebitPostedDate.Value));
            //     }
            //     if (r.CreditPostedDate != null && creditAccountId != null)
            //     {
            //         postings.Add((creditAccountId, r.CreditPostedDate.Value));
            //     }
            //     break;
            default:
                break;
        }
        return postings;
    }

    /// <summary>
    /// Sets the posted date on the appropriate property of the transaction
    /// </summary>
    private static void SetPostedDate(Transaction transaction, AccountId account, DateOnly postedDate)
    {
        switch (transaction)
        {
            case SpendingTransferTransaction spendingTransfer when spendingTransfer.CreditAccountId == account:
                spendingTransfer.CreditPostedDate = postedDate;
                break;
            case SpendingTransaction spending:
                spending.PostedDate = postedDate;
                break;
            case IncomeTransferTransaction incomeTransfer when incomeTransfer.DebitAccountId == account:
                incomeTransfer.DebitPostedDate = postedDate;
                break;
            case IncomeTransaction income:
                income.PostedDate = postedDate;
                break;
            case TransferTransaction transfer when transfer.DebitAccountId == account:
                transfer.DebitPostedDate = postedDate;
                break;
            case TransferTransaction transfer:
                transfer.CreditPostedDate = postedDate;
                break;
            // case RefundTransaction refund:
            //     AccountId? firstAccountId = refund.GetAllAffectedAccountIds().FirstOrDefault();
            //     if (firstAccountId == account)
            //     {
            //         refund.DebitPostedDate = postedDate;
            //     }
            //     else
            //     {
            //         refund.CreditPostedDate = postedDate;
            //     }
            //     break;
            default:
                break;
        }
    }

    /// <summary>
    /// Clears the posted date on the appropriate property of the transaction
    /// </summary>
    private static void ClearPostedDate(Transaction transaction, AccountId account)
    {
        switch (transaction)
        {
            case SpendingTransferTransaction spendingTransfer when spendingTransfer.CreditAccountId == account:
                spendingTransfer.CreditPostedDate = null;
                break;
            case SpendingTransaction spending:
                spending.PostedDate = null;
                break;
            case IncomeTransferTransaction incomeTransfer when incomeTransfer.DebitAccountId == account:
                incomeTransfer.DebitPostedDate = null;
                break;
            case IncomeTransaction income:
                income.PostedDate = null;
                break;
            case TransferTransaction transfer when transfer.DebitAccountId == account:
                transfer.DebitPostedDate = null;
                break;
            case TransferTransaction transfer:
                transfer.CreditPostedDate = null;
                break;
            // case RefundTransaction refund:
            //     refund.DebitPostedDate = null;
            //     refund.CreditPostedDate = null;
            //     break;
            default:
                break;
        }
    }

    /// <summary>
    /// Validates the Accounting Period for this Transaction
    /// </summary>
    private bool ValidateAccountingPeriod(CreateTransactionRequest request, AccountingPeriod accountingPeriod, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!accountingPeriod.IsOpen)
        {
            exceptions = exceptions.Append(new InvalidAccountingPeriodException("The Accounting Period is closed."));
        }
        foreach (Account account in GetRequestAccounts(request))
        {
            AccountingPeriod accountInitialPeriod = accountingPeriodRepository.GetById(account.AddAccountingPeriodId);
            if (accountingPeriod.PeriodStartDate < accountInitialPeriod.PeriodStartDate)
            {
                exceptions = exceptions.Append(new InvalidAccountingPeriodException("An Account did not exist during the provided Accounting Period."));
            }
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the Date for this Transaction
    /// </summary>
    private static bool ValidateDate(
        AccountingPeriod accountingPeriod,
        IEnumerable<Account> accounts,
        DateOnly date,
        out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (date == DateOnly.MinValue)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is blank."));
        }
        if (!accountingPeriod.IsDateInPeriod(date))
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is not within the transaction's accounting period."));
        }
        foreach (Account account in accounts)
        {
            if (date < account.AddDate)
            {
                exceptions = exceptions.Append(new InvalidDateException("The provided date is before the account was created."));
            }
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the fund amounts for a new Transaction
    /// </summary>
    private static bool ValidateFundAmounts(CreateTransactionRequest request, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (request is CreateSpendingTransactionRequest spendingRequest)
        {
            if (spendingRequest.FundAssignments.Count == 0)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided list of fund amounts is empty."));
            }
            if (spendingRequest.FundAssignments.Any(fundAmount => fundAmount.Amount <= 0))
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided fund amounts must be greater than zero."));
            }
        }
        else if (request is CreateIncomeTransactionRequest incomeRequest && incomeRequest.FundAssignments.Any(fundAmount => fundAmount.Amount <= 0))
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("The provided fund amounts must be greater than zero."));
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the fund amounts for an updated Transaction
    /// </summary>
    private static bool ValidateFundAmountsForUpdate(UpdateTransactionRequest request, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (request is UpdateSpendingTransactionRequest spendingRequest)
        {
            if (spendingRequest.FundAssignments.Count == 0)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided list of fund amounts is empty."));
            }
            if (spendingRequest.FundAssignments.Any(fundAmount => fundAmount.Amount <= 0))
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided fund amounts must be greater than zero."));
            }
        }
        else if (request is UpdateIncomeTransactionRequest incomeRequest && incomeRequest.FundAssignments.Any(fundAmount => fundAmount.Amount <= 0))
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("The provided fund amounts must be greater than zero."));
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the posting of this Transaction within an Account
    /// </summary>
    private bool ValidatePosting(
        Transaction transaction,
        AccountId account,
        DateOnly postedDate,
        out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!transaction.GetAllAffectedAccountIds().Contains(account))
        {
            exceptions = exceptions.Append(new InvalidAccountException("The provided account is not associated with this transaction."));
            return false;
        }
        if (transaction.GetPostedDateForAccount(account) != null)
        {
            exceptions = exceptions.Append(new UnableToPostException("The Transaction has already been posted to this Account."));
            return !exceptions.Any();
        }
        if (postedDate < transaction.Date)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is earlier than the transaction date."));
        }
        AccountingPeriod accountingPeriod = accountingPeriodRepository.GetById(transaction.AccountingPeriodId);
        int monthDifference = Math.Abs(((accountingPeriod.Year - postedDate.Year) * 12) + accountingPeriod.Month - postedDate.Month);
        if (monthDifference > 1)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is not within the transaction's accounting period."));
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates that the Transaction has not been posted to either Account
    /// </summary>
    private static bool ValidateNotPosted(Transaction transaction, AccountId? accountBeingDeleted)
    {
        foreach (AccountId accountId in transaction.GetAllAffectedAccountIds())
        {
            if (accountId != accountBeingDeleted && transaction.GetPostedDateForAccount(accountId) != null)
            {
                return false;
            }
        }
        return true;
    }

    /// <summary>
    /// Validates the unposting of this Transaction
    /// </summary>
    private bool ValidateUnposting(Transaction transaction, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!accountingPeriodRepository.GetById(transaction.AccountingPeriodId).IsOpen)
        {
            exceptions = exceptions.Append(new UnableToUnpostException("The Transaction's Accounting Period is closed."));
        }
        if (transaction.GetAllAffectedAccountIds().All(id => transaction.GetPostedDateForAccount(id) == null))
        {
            exceptions = exceptions.Append(new UnableToUnpostException("The Transaction has not been posted to either account."));
        }
        if (GetGeneratedByAccountId(transaction) != null)
        {
            exceptions = exceptions.Append(new UnableToUnpostException("The provided transaction was auto-generated by an account."));
        }
        return !exceptions.Any();
    }
}
