using System.Diagnostics.CodeAnalysis;
using Domain.AccountingPeriods;
using Domain.Accounts;
using Domain.Budgets;
using Domain.Exceptions;
using Domain.Funds;

namespace Domain.Transactions;

/// <summary>
/// Service for managing Transactions
/// </summary>
public class TransactionService(
    AccountBalanceService accountBalanceService,
    AccountingPeriodBalanceService accountingPeriodBalanceService,
    BudgetBalanceService budgetBalanceService,
    FundBalanceService fundBalanceService,
    IAccountingPeriodRepository accountingPeriodRepository,
    IAccountRepository accountRepository,
    ITransactionRepository transactionRepository)
{
    /// <summary>
    /// Attempts to create a new Transaction
    /// </summary>
    public bool TryCreate(CreateTransactionRequest request, [NotNullWhen(true)] out Transaction? transaction, out IEnumerable<Exception> exceptions)
    {
        transaction = null;
        exceptions = [];

        if (!ValidateAccountingPeriod(request, out IEnumerable<Exception> accountingPeriodExceptions))
        {
            exceptions = exceptions.Concat(accountingPeriodExceptions);
        }
        if (!ValidateDate(request.AccountingPeriod,
                request.DebitAccount?.Account,
                request.CreditAccount?.Account,
                request.Date,
                out IEnumerable<Exception> dateExceptions))
        {
            exceptions = exceptions.Concat(dateExceptions);
        }
        if (!ValidateAccountAmounts(request.DebitAccount?.Account.Id,
                request.DebitAccount?.FundAmounts.ToList(),
                request.DebitAccount?.BudgetAmounts.ToList(),
                request.CreditAccount?.Account.Id,
                request.CreditAccount?.FundAmounts.ToList(),
                request.CreditAccount?.BudgetAmounts.ToList(),
                out IEnumerable<Exception> accountExceptions))
        {
            exceptions = exceptions.Concat(accountExceptions);
        }
        if (exceptions.Any())
        {
            return false;
        }
        transaction = new Transaction(request, transactionRepository.GetNextSequenceForDate(request.Date));
        accountBalanceService.AddTransaction(transaction);
        fundBalanceService.AddTransaction(transaction);
        budgetBalanceService.AddTransaction(transaction);
        transactionRepository.Add(transaction);
        if (request.DebitAccount?.PostedDate != null && !TryPost(transaction, request.DebitAccount.Account.Id, request.DebitAccount.PostedDate.Value, out IEnumerable<Exception> debitPostingExceptions))
        {
            exceptions = exceptions.Concat(debitPostingExceptions);
        }
        if (request.CreditAccount?.PostedDate != null && !TryPost(transaction, request.CreditAccount.Account.Id, request.CreditAccount.PostedDate.Value, out IEnumerable<Exception> creditPostingExceptions))
        {
            exceptions = exceptions.Concat(creditPostingExceptions);
        }
        if (exceptions.Any())
        {
            return false;
        }
        return true;
    }

    /// <summary>
    /// Attempts to update an existing Transaction
    /// </summary>
    public bool TryUpdate(Transaction transaction, UpdateTransactionRequest request, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (transaction.GeneratedByAccountId != null)
        {
            exceptions = exceptions.Append(new UnableToUpdateException("The provided transaction was auto-generated by an account and cannot be updated."));
        }
        if (!ValidateNotPosted(transaction, null))
        {
            exceptions = exceptions.Append(new UnableToUpdateException("The provided transaction has already been posted to an account."));
        }
        if (!ValidateDate(accountingPeriodRepository.GetById(transaction.AccountingPeriodId),
                transaction.DebitAccount != null ? accountRepository.GetById(transaction.DebitAccount.AccountId) : null,
                transaction.CreditAccount != null ? accountRepository.GetById(transaction.CreditAccount.AccountId) : null,
                request.Date,
                out IEnumerable<Exception> dateExceptions))
        {
            exceptions = exceptions.Concat(dateExceptions);
        }
        if (!ValidateAccountAmounts(transaction.DebitAccount?.AccountId,
                request.DebitAccount?.FundAmounts.ToList(),
                request.DebitAccount?.BudgetAmounts.ToList(),
                transaction.CreditAccount?.AccountId,
                request.CreditAccount?.FundAmounts.ToList(),
                request.CreditAccount?.BudgetAmounts.ToList(),
                out IEnumerable<Exception> accountExceptions))
        {
            exceptions = exceptions.Concat(accountExceptions);
        }
        if (exceptions.Any())
        {
            return false;
        }
        transaction.Date = request.Date;
        transaction.Location = request.Location;
        transaction.Description = request.Description;
        if (transaction.DebitAccount != null && request.DebitAccount != null)
        {
            transaction.DebitAccount = new TransactionAccount(transaction, transaction.DebitAccount.AccountId, TransactionAccountType.Debit,
                request.DebitAccount.FundAmounts, request.DebitAccount.BudgetAmounts);
        }
        if (transaction.CreditAccount != null && request.CreditAccount != null)
        {
            transaction.CreditAccount = new TransactionAccount(transaction, transaction.CreditAccount.AccountId, TransactionAccountType.Credit,
                request.CreditAccount.FundAmounts, request.CreditAccount.BudgetAmounts);
        }
        accountBalanceService.UpdateTransaction(transaction);
        fundBalanceService.UpdateTransaction(transaction);
        budgetBalanceService.UpdateTransaction(transaction);
        if (request.DebitAccount?.PostedDate != null &&
            transaction.DebitAccount != null &&
            !TryPost(transaction, transaction.DebitAccount.AccountId, request.DebitAccount.PostedDate.Value, out IEnumerable<Exception> debitPostingExceptions))
        {
            exceptions = exceptions.Concat(debitPostingExceptions);
        }
        if (request.CreditAccount?.PostedDate != null &&
            transaction.CreditAccount != null &&
            !TryPost(transaction, transaction.CreditAccount.AccountId, request.CreditAccount.PostedDate.Value, out IEnumerable<Exception> creditPostingExceptions))
        {
            exceptions = exceptions.Concat(creditPostingExceptions);
        }
        if (exceptions.Any())
        {
            return false;
        }
        return true;
    }

    /// <summary>
    /// Attempts to post an existing Transaction within an Account
    /// </summary>
    public bool TryPost(Transaction transaction, AccountId account, DateOnly postedDate, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!ValidatePosting(transaction, account, postedDate, out TransactionAccount? transactionAccount, out IEnumerable<Exception> postingExceptions))
        {
            exceptions = exceptions.Concat(postingExceptions);
            return false;
        }
        if (transaction.DebitAccount != null && transaction.CreditAccount != null && transaction.DebitAccount.AccountId == transaction.CreditAccount.AccountId)
        {
            transaction.DebitAccount.PostedDate = postedDate;
            transaction.CreditAccount.PostedDate = postedDate;
            accountingPeriodBalanceService.PostTransaction(transaction.DebitAccount);
            accountingPeriodBalanceService.PostTransaction(transaction.CreditAccount);
        }
        else
        {
            transactionAccount.PostedDate = postedDate;
            accountingPeriodBalanceService.PostTransaction(transactionAccount);
        }
        accountBalanceService.PostTransaction(transaction, transactionAccount);
        fundBalanceService.PostTransaction(transaction, transactionAccount);
        budgetBalanceService.PostTransaction(transaction, transactionAccount);
        return true;
    }

    /// <summary>
    /// Attempts to unpost an existing Transaction within an Account
    /// </summary>
    public bool TryUnpost(Transaction transaction, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!ValidateUnposting(transaction, out IEnumerable<Exception> unpostingExceptions))
        {
            exceptions = exceptions.Concat(unpostingExceptions);
            return false;
        }
        if (transaction.DebitAccount != null)
        {
            accountingPeriodBalanceService.UnpostTransaction(transaction.DebitAccount);
            transaction.DebitAccount.PostedDate = null;
            accountBalanceService.UnpostTransaction(transaction, transaction.DebitAccount);
            fundBalanceService.UnpostTransaction(transaction, transaction.DebitAccount);
            budgetBalanceService.UnpostTransaction(transaction, transaction.DebitAccount);
        }
        if (transaction.CreditAccount != null)
        {
            accountingPeriodBalanceService.UnpostTransaction(transaction.CreditAccount);
            transaction.CreditAccount.PostedDate = null;
            accountBalanceService.UnpostTransaction(transaction, transaction.CreditAccount);
            fundBalanceService.UnpostTransaction(transaction, transaction.CreditAccount);
            budgetBalanceService.UnpostTransaction(transaction, transaction.CreditAccount);
        }
        return true;
    }

    /// <summary>
    /// Attempts to delete an existing Transaction
    /// </summary>
    public bool TryDelete(Transaction transaction, AccountId? accountBeingDeleted, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (accountBeingDeleted != transaction.GeneratedByAccountId && transaction.GeneratedByAccountId != null)
        {
            exceptions = exceptions.Append(new UnableToDeleteException("The provided transaction was auto-generated by an account."));
        }
        if (!accountingPeriodRepository.GetById(transaction.AccountingPeriodId).IsOpen)
        {
            exceptions = exceptions.Append(new UnableToDeleteException("The provided transaction is within a closed accounting period."));
        }
        if (!ValidateNotPosted(transaction, accountBeingDeleted))
        {
            exceptions = exceptions.Append(new UnableToDeleteException("The provided transaction has already been posted to an account."));
        }
        if (exceptions.Any())
        {
            return false;
        }
        accountBalanceService.DeleteTransaction(transaction);
        fundBalanceService.DeleteTransaction(transaction);
        budgetBalanceService.DeleteTransaction(transaction);
        transactionRepository.Delete(transaction);
        return true;
    }

    /// <summary>
    /// Validates the Accounting Period for this Transaction
    /// </summary>
    private bool ValidateAccountingPeriod(CreateTransactionRequest request, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!request.AccountingPeriod.IsOpen)
        {
            exceptions = exceptions.Append(new InvalidAccountingPeriodException("The Accounting Period is closed."));
        }
        if (request.DebitAccount != null)
        {
            AccountingPeriod debitAccountInitialPeriod = accountingPeriodRepository.GetById(request.DebitAccount.Account.AddAccountingPeriodId);
            if (request.AccountingPeriod.PeriodStartDate < debitAccountInitialPeriod.PeriodStartDate)
            {
                exceptions = exceptions.Append(new InvalidAccountingPeriodException("The Debit Account did not exist during the provided Accounting Period."));
            }
        }
        if (request.CreditAccount != null)
        {
            AccountingPeriod creditAccountInitialPeriod = accountingPeriodRepository.GetById(request.CreditAccount.Account.AddAccountingPeriodId);
            if (request.AccountingPeriod.PeriodStartDate < creditAccountInitialPeriod.PeriodStartDate)
            {
                exceptions = exceptions.Append(new InvalidAccountingPeriodException("The Credit Account did not exist during the provided Accounting Period."));
            }
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the Date for this Transaction
    /// </summary>
    private static bool ValidateDate(
        AccountingPeriod accountingPeriod,
        Account? debitAccount,
        Account? creditAccount,
        DateOnly date,
        out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (date == DateOnly.MinValue)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is blank."));
        }
        if (!accountingPeriod.IsDateInPeriod(date))
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is not within the transaction's accounting period."));
        }
        if (debitAccount != null && date < debitAccount.AddDate)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is before the debit account was created."));
        }
        if (creditAccount != null && date < creditAccount.AddDate)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is before the credit account was created."));
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the amounts for each Account for this Transaction
    /// </summary>
    private static bool ValidateAccountAmounts(
        AccountId? debitAccount,
        List<FundAmount>? debitFundAmounts,
        List<BudgetAmount>? debitBudgetAmounts,
        AccountId? creditAccount,
        List<FundAmount>? creditFundAmounts,
        List<BudgetAmount>? creditBudgetAmounts,
        out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (debitFundAmounts == null && debitBudgetAmounts == null && creditFundAmounts == null && creditBudgetAmounts == null)
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("No amounts were provided"));
        }
        if (debitAccount != null && debitFundAmounts == null && debitBudgetAmounts == null)
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("No amounts were provided for the debit account."));
        }
        if (debitAccount == null && (debitFundAmounts != null || debitBudgetAmounts != null))
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("Debit amounts were provided but no debit account exists."));
        }
        if (creditAccount != null && creditFundAmounts == null && creditBudgetAmounts == null)
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("No amounts were provided for the credit account."));
        }
        if (creditAccount == null && (creditFundAmounts != null || creditBudgetAmounts != null))
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("Credit amounts were provided but no credit account exists."));
        }
        if (debitAccount == creditAccount && debitFundAmounts != null && creditFundAmounts != null &&
            debitFundAmounts.Any(debitFund => creditFundAmounts.Select(fundAmount => fundAmount.FundId).Contains(debitFund.FundId)))
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("The same fund cannot be both debited and credited for a transaction within a single account."));
        }
        if (debitAccount == creditAccount && debitBudgetAmounts != null && creditBudgetAmounts != null &&
            debitBudgetAmounts.Any(debitBudget => creditBudgetAmounts.Select(budgetAmount => budgetAmount.Budget.Id).Contains(debitBudget.Budget.Id)))
        {
            exceptions = exceptions.Append(new InvalidFundAmountException("The same budget cannot be both debited and credited for a transaction within a single account."));
        }
        if (debitFundAmounts != null)
        {
            if (debitFundAmounts.Count == 0)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided list of debit fund amounts is empty."));
            }
            if (debitFundAmounts.Any(fundAmount => fundAmount.Amount <= 0))
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided debit fund amounts must be greater than zero."));
            }
        }
        if (debitBudgetAmounts != null)
        {
            if (debitBudgetAmounts.Count == 0)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided list of debit budget amounts is empty."));
            }
            if (debitBudgetAmounts.Any(budgetAmount => budgetAmount.Amount <= 0))
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided debit budget amounts must be greater than zero."));
            }
        }
        if (creditFundAmounts != null)
        {
            if (creditFundAmounts.Count == 0)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided list of credit fund amounts is empty."));
            }
            if (creditFundAmounts.Any(fundAmount => fundAmount.Amount <= 0))
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided credit fund amounts must be greater than zero."));
            }
        }
        if (creditBudgetAmounts != null)
        {
            if (creditBudgetAmounts.Count == 0)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided list of credit budget amounts is empty."));
            }
            if (creditBudgetAmounts.Any(budgetAmount => budgetAmount.Amount <= 0))
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided credit budget amounts must be greater than zero."));
            }
        }
        if ((debitFundAmounts != null || debitBudgetAmounts != null) && (creditFundAmounts != null || creditBudgetAmounts != null))
        {
            decimal totalDebit = (debitFundAmounts?.Sum(fundAmount => fundAmount.Amount) ?? 0) + (debitBudgetAmounts?.Sum(budgetAmount => budgetAmount.Amount) ?? 0);
            decimal totalCredit = (creditFundAmounts?.Sum(fundAmount => fundAmount.Amount) ?? 0) + (creditBudgetAmounts?.Sum(budgetAmount => budgetAmount.Amount) ?? 0);
            if (totalDebit != totalCredit)
            {
                exceptions = exceptions.Append(new InvalidFundAmountException("The provided debit and credit amounts sum to different totals."));
            }
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates the posting of this Transaction within an Account
    /// </summary>
    private bool ValidatePosting(
        Transaction transaction,
        AccountId account,
        DateOnly postedDate,
        [NotNullWhen(true)] out TransactionAccount? transactionAccount,
        out IEnumerable<Exception> exceptions)
    {
        transactionAccount = null;
        exceptions = [];

        if (transaction.DebitAccount != null && transaction.DebitAccount.AccountId == account)
        {
            transactionAccount = transaction.DebitAccount;
        }
        else if (transaction.CreditAccount != null && transaction.CreditAccount.AccountId == account)
        {
            transactionAccount = transaction.CreditAccount;
        }
        else
        {
            exceptions = exceptions.Append(new InvalidAccountException("The provided account is not associated with this transaction."));
            return false;
        }
        if (transactionAccount.PostedDate != null)
        {
            exceptions = exceptions.Append(new UnableToPostException("The Transaction has already been posted to this Account."));
            return !exceptions.Any();
        }
        if (postedDate < transaction.Date)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is earlier than the transaction date."));
        }
        if (transaction.DebitAccount?.AccountId == transaction.CreditAccount?.AccountId && postedDate != transaction.Date)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date must be the same as the transaction date when posting to the same account."));
        }
        AccountingPeriod accountingPeriod = accountingPeriodRepository.GetById(transaction.AccountingPeriodId);
        int monthDifference = Math.Abs(((accountingPeriod.Year - postedDate.Year) * 12) + accountingPeriod.Month - postedDate.Month);
        if (monthDifference > 1)
        {
            exceptions = exceptions.Append(new InvalidDateException("The provided date is not within the transaction's accounting period."));
        }
        return !exceptions.Any();
    }

    /// <summary>
    /// Validates that the Transaction has not been posted to either Account
    /// </summary>
    private static bool ValidateNotPosted(Transaction transaction, AccountId? accountBeingDeleted)
    {
        if (transaction.DebitAccount != null && accountBeingDeleted != transaction.DebitAccount.AccountId && transaction.DebitAccount.PostedDate != null)
        {
            return false;
        }
        if (transaction.CreditAccount != null && accountBeingDeleted != transaction.CreditAccount.AccountId && transaction.CreditAccount.PostedDate != null)
        {
            return false;
        }
        return true;
    }

    /// <summary>
    /// Validates the unposting of this Transaction within an Account
    /// </summary>
    private bool ValidateUnposting(Transaction transaction, out IEnumerable<Exception> exceptions)
    {
        exceptions = [];

        if (!accountingPeriodRepository.GetById(transaction.AccountingPeriodId).IsOpen)
        {
            exceptions = exceptions.Append(new UnableToUnpostException("The Transaction's Accounting Period is closed."));
        }
        if ((transaction.DebitAccount == null || transaction.DebitAccount.PostedDate == null) &&
            (transaction.CreditAccount == null || transaction.CreditAccount.PostedDate == null))
        {
            exceptions = exceptions.Append(new UnableToUnpostException("The Transaction has not been posted to either account."));
        }
        if (transaction.GeneratedByAccountId != null)
        {
            exceptions = exceptions.Append(new UnableToUnpostException("The provided transaction was auto-generated by an account."));
        }
        return !exceptions.Any();
    }
}