# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./backend/Backend.sln
    - name: Verify formatting
      run: dotnet format ./backend/Backend.sln --verify-no-changes --no-restore --severity info
    - name: Build
      run: dotnet build ./backend/Backend.sln --no-restore
    - name: Test
      run: dotnet test ./backend/Backend.sln --no-build --verbosity normal
